// services/react-client/src/components/add-user.js
import React from 'react';

const AddUser = ({ addUser, handleChange, username, email }) => {
  return (
    <form onSubmit={(event) => addUser(event)}>
      <div className="field">
        <input
          value={username}
          type="text"
          className="input is-large"
          name="username"
          placeholder="Enter username"
          onChange={handleChange}
          required/>
      </div>
      <div className="field">
        <input
          value={email}
          type="text"
          className="input is-large"
          name="email"
          placeholder="Enter email"
          onChange={handleChange}
          required/>
      </div>
      <div>
        <input type="submit" value="Submit" className="button is-primary is-large is-fullwidth"/>
      </div>
    </form>
  );
};
export default AddUser;

// services/vue-ui/src/components/add-user.vue
<template>
  <form @submit.prevent="onSubmit">
    <div class="form-group">
      <input
        type="text"
        class="form-control input-lg"
        required
        name="username"
        placeholder="Enter a username"
        v-model="username"
      >
      <input
        type="text"
        class="form-control input-lg"
        required
        name="email"
        placeholder="Enter an email address"
        v-model="email"
      >
      <input
        type="submit"
        class="btn btn-primary btn-lg btn-block"
        value="Submit"
      >
    </div>
  </form>
</template>
<script>
export default {
  data() {
    return {
      email: '',
      username: '',
    };
  },
  methods: {
    onSubmit() {
      this.$emit('formSubmit', {
        username: this.username,
        email: this.email,
      });
    },
  },
};
</script>
