// services/vue-ui/src/components/add-user.vue
<template>
  <form @submit.prevent="onSubmit">
    <div class="form-group">
      <input
        type="text"
        class="form-control input-lg"
        required
        name="username"
        placeholder="Enter a username"
        v-model="username"
      >
      <input
        type="text"
        class="form-control input-lg"
        required
        name="email"
        placeholder="Enter an email address"
        v-model="email"
      >
      <input
        type="submit"
        class="btn btn-primary btn-lg btn-block"
        value="Submit"
      >
    </div>
  </form>
</template>
<script>
export default {
  data() {
    return {
      email: '',
      username: '',
    };
  },
  methods: {
    onSubmit() {
      this.$emit('formSubmit', {
        username: this.username,
        email: this.email,
      });
    },
  },
};
</script>

// services/react-ui/src/components/add-user.js
import React from 'react';
import PropTypes from 'prop-types';

const AddUser = (props) => {
  return (
    <form onSubmit={(e) => props.addUser(e)}>
      <div className="form-group">
        <input
          name="username"
          className="form-control input-lg"
          type="text"
          required
          placeholder="Enter a username"
          value={props.username}
          onChange={props.handleChange}
        />
        <input
          name="email"
          className="form-control input-lg"
          type="text"
          required
          placeholder="Enter an email address"
          value={props.email}
          onChange={props.handleChange}
        />
        <input
          className="btn btn-primary btn-lg btn-block"
          type="submit"
          value="Submit"
        />
      </div>
    </form>
  )
};
AddUser.propTypes = {
  addUser: PropTypes.func,
  handleChange: PropTypes.func,
  email: PropTypes.string,
  username: PropTypes.string,
}

export default AddUser;
